var imagelist = 
{ mediagallery :
  { gallerywidth:575,
    galleryheight:675,
    gallerypadding:30,
    categoryareaheight:20,
    categoryscrolltype:"fixed",
    categoryscrollspeed:10,
    categoryscrollbuffer:150,
    thumbwidth:125,
    thumbheight:125,
    thumbspacing:5,
    thumbrows:4,
    thumbcolumns:4,
    thumbscaleup:1.2,
    thumbfxstrength:3,
    thumbblurstrength:8,
    thumbshadowstrength:10,
    thumbshadowopacity:0.2,
    thumbiconcolor:1650754,
    thumbiconbgcolor:5942468,
    thumbiconopacity:1,
    backgroundpatterncolor:5942468,
    backgroundpatternopacity:0,
    solidbackgroundcolor:10336449,
    solidbackgroundopacity:0,
    gallerybackgroundcolor:16777215,
    gallerybackgroundopacity:1,
    preloadoverlaycolor:1650754,
    preloadoverlayopacity:0.92,
    selectarrowcolor:16777215,
    selectarrowshadowopacity:1,
    nextpreviousareawidth:130,
    categoryfontsize:20,
    categoryspacing:-2,
    categoryidleopacity:0.3,
    categoryselectcolor:1650754,
    categoryshadowopacity:1,
    categoryfont:"Bebas Neue",
    descriptionfont:"ColaborateLight",
    
    category:[
        {  title:"1.VERDENSKRIG ALLIERTE |",
           entry:[
              {"entrytype":"image",
              "entrylink":"images/P002.jpg",
              "entrythumblink":"thumbs/P002.jpg",
              "videopreviewimage":"",
              "$t":"&lt;h1&gt;P002 | Amerikansk propagandaplakat 1917&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:%27Destroy_this_mad_brute%27_WWI_propaganda_poster_%28US_version%29.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

              {"entrytype":"image",
              "entrylink":"images/P003.jpg",
              "entrythumblink":"thumbs/P003.jpg",
              "videopreviewimage":"",
              "$t":"&lt;h1&gt;P003 | Amerikansk propagandaplakat 1917&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Anti-duitse-propaganda-WO-I.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

              {"entrytype":"image",
              "entrylink":"images/P004.jpg",
              "entrythumblink":"thumbs/P004.jpg",
              "videopreviewimage":"",
              "$t":"&lt;h1&gt;P004 | Amerikansk propagandaplakat 1.verdenskrig&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Remember_the_Bond_propaganda_poster_by_Oscar_Cesare_c1916.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

              {"entrytype":"image",
              "entrylink":"images/P005.jpg",
              "entrythumblink":"thumbs/P005.jpg",
              "videopreviewimage":"",
              "$t":"&lt;h1&gt;P005 | Engelsk propagandaplakat 1915&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Flickr_-_%E2%80%A6trialsanderrors_-_Step_into_your_place,_propaganda_poster,_1915.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

              {"entrytype":"image",
              "entrylink":"images/P006.jpg",
              "entrythumblink":"thumbs/P006.jpg",
              "videopreviewimage":"",
              "$t":"&lt;h1&gt;P006 | Amerikansk propagandaplakat 1918&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Joan_of_Arc-T.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

              {"entrytype":"image",
              "entrylink":"images/P007.jpg",
              "entrythumblink":"thumbs/P007.jpg",
              "videopreviewimage":"",
              "$t":"&lt;h1&gt;P007 | Engelsk propagandaplakat 1915&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Daddy_in_the_great_war.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

              {"entrytype":"image",
              "entrylink":"images/P008.jpg",
              "entrythumblink":"thumbs/P008.jpg",
              "videopreviewimage":"",
              "$t":"&lt;h1&gt;P008 | Amerikansk propagandaplakat 1.verdenskrig&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:TogetherWeWinJMFlaggWWI.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

              {"entrytype":"image",
              "entrylink":"images/P009.jpg",
              "entrythumblink":"thumbs/P009.jpg",
              "videopreviewimage":"",
              "$t":"&lt;h1&gt;P009 | Alliert propagandaplakat 1918&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Every_girl_pulling_for_victory,_WWI_poster,_1918.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

              {"entrytype":"image",
              "entrylink":"images/P010.jpg",
              "entrythumblink":"thumbs/P010.jpg",
              "videopreviewimage":"",
              "$t":"&lt;h1&gt;P010 | Amerikansk propagandaplakat 1918&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Remember_Belgium.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

              {"entrytype":"image",
              "entrylink":"images/P011.jpg",
              "entrythumblink":"thumbs/P011.jpg",
              "videopreviewimage":"",
              "$t":"&lt;h1&gt;P011 | Amerikansk propagandaplakat 1917&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Amorsoloposter.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

              {"entrytype":"image",
              "entrylink":"images/P012.jpg",
              "entrythumblink":"thumbs/P012.jpg",
              "videopreviewimage":"",
              "$t":"&lt;h1&gt;P012 | Russisk propagandaplakat 1914&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:StGeorge1914.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

              {"entrytype":"image",
              "entrylink":"images/P013.jpg",
              "entrythumblink":"thumbs/P013.jpg",
              "videopreviewimage":"",
              "$t":"&lt;h1&gt;P013 | Britisk rekrutteringsplakat 1.verdenskrig&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Kitchener-Britons.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

              {"entrytype":"image",
              "entrylink":"images/P014.jpg",
              "entrythumblink":"thumbs/P014.jpg",
              "videopreviewimage":"",
              "$t":"&lt;h1&gt;P014 | Amerikansk rekrutteringsplakat 1.verdenskrig&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Unclesamwantyou.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

              {"entrytype":"image",
              "entrylink":"images/P015.jpg",
              "entrythumblink":"thumbs/P015.jpg",
              "videopreviewimage":"",
              "$t":"&lt;h1&gt;P015 | Amerikansk filmplakat 1918&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Hearts_of_the_World_poster.jpg?uselang=nn&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

              {"entrytype":"image",
              "entrylink":"images/P016.jpg",
              "entrythumblink":"thumbs/P016.jpg",
              "videopreviewimage":"",
              "$t":"&lt;h1&gt;P016 | Australsk propagandaplakat 1918&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Lindsay_German_monster.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"}
          ]
        },

        {   "title":"1.VERDENSKRIG TYSKLAND |",
            "entry":[
              {"entrytype":"image",
              "entrylink":"images/P020.jpg",
              "entrythumblink":"thumbs/P020.jpg",
              "videopreviewimage":"",
              "$t":"&lt;h1&gt;P020 | Propagandapostkort Østerrike-Ungarn 1914&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Dreschplatz.JPG &apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

              {"entrytype":"image",
              "entrylink":"images/P021.jpg",
              "entrythumblink":"thumbs/P021.jpg",
              "videopreviewimage":"",
              "$t":"&lt;h1&gt;P021 | Tysk postkort 1915&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Wachsoldat.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

              {"entrytype":"image",
              "entrylink":"images/P023.jpg",
              "entrythumblink":"thumbs/P023.jpg",
              "videopreviewimage":"",
              "$t":"&lt;h1&gt;P023 | Tysk postkort 1917 &lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Toter_Krieger.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

              {"entrytype":"image",
              "entrylink":"images/P024.jpg",
              "entrythumblink":"thumbs/P024.jpg",
              "videopreviewimage":"",
              "$t":"&lt;h1&gt;P024 | Tysk postkort 1915&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Die_Sonne_sank_im_Westen.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

              {"entrytype":"image",
              "entrylink":"images/P025.jpg",
              "entrythumblink":"thumbs/P025.jpg",
              "videopreviewimage":"",
              "$t":"&lt;h1&gt;P025 | Postkort 1.verdenskrig som viser de regjerende fyrstene i alliansen&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Central_Powers_monarchs_postcard.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

              {"entrytype":"image",
              "entrylink":"images/P026.jpg",
              "entrythumblink":"thumbs/P026.jpg",
              "videopreviewimage":"",
              "$t":"&lt;h1&gt;P026 | Østerrisk-ungarsk plakat 1918&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Julius_Klinger_WWI_poster.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

              {"entrytype":"image",
              "entrylink":"images/P027.jpg",
              "entrythumblink":"thumbs/P027.jpg",
              "videopreviewimage":"",
              "$t":"&lt;h1&gt;P027 | Tysk propagandaplakat 1917&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Helft_uns_siegen.jpg &apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

              {"entrytype":"image",
              "entrylink":"images/P028.jpg",
              "entrythumblink":"thumbs/P028.jpg",
              "videopreviewimage":"",
              "$t":"&lt;h1&gt;P028 | Tysk plakat 1918&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:WWIposter6.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

              {"entrytype":"image",
              "entrylink":"images/P029.jpg",
              "entrythumblink":"thumbs/P029.jpg",
              "videopreviewimage":"",
              "$t":"&lt;h1&gt;P029 | Tysk propagandaplakat 1917&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:WWIposter12.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"}
          ]
        },

        {"title":"MELLOMKRIGSTIDEN |",
        "entry":[
        {"entrytype":"image",
        "entrylink":"images/P035.jpg",
        "entrythumblink":"thumbs/P035.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P035 | Plakat fra den spanske borgerkrigen 1930-tallet&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Fascismo.jpg &apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P036.jpg",
        "entrythumblink":"thumbs/P036.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P036 | Antijapansk plakat 1930-tallet&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:NRA_anti-Japanese_war_poster.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P037.jpg",
        "entrythumblink":"thumbs/P037.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P037 | Japansk propagandaplakat for “befrielsen” av Mandsjuria 1935&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Manchukuo011.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P038.jpg",
        "entrythumblink":"thumbs/P038.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P038 | Sovjetisk propagandaplakat 1920-årene&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Poster15.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P039.jpg",
        "entrythumblink":"thumbs/P039.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P039 | Rekrutteringsplakat til den russiske borgerkrigen 1918–20&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Denikin_poster.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P040.jpg",
        "entrythumblink":"thumbs/P040.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P040 | Tysk propagandaplakat 1934&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Luftschutz.png &apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P041.jpg",
        "entrythumblink":"thumbs/P041.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P041 | Tysk propagandaplakat 1939&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Nazi_World_War_II_poster_Danzig_is_German.jpg\t&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P042.jpg",
        "entrythumblink":"thumbs/P042.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P042 | Sovjetisk 1.mai plakat 1920&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:1mei.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P043.jpg",
        "entrythumblink":"thumbs/P043.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P043 | Sovjetisk 1.mai-plakat 1929&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Soviet_May_day_1929.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P044.jpg",
        "entrythumblink":"thumbs/P044.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P044 | Hviterussisk propagandaplakat 1919&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:WhiteArmyPropagandaPosterOfTrotsky.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P045.jpg",
        "entrythumblink":"thumbs/P045.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P045 | Tysk valgplakat 1919&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:WWIposter2.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P046.jpg",
        "entrythumblink":"thumbs/P046.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P046 | Svensk valgplakat 1928&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Svensk_samling.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P047.jpg",
        "entrythumblink":"thumbs/P047.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P047 | Amerikansk propagandaplakat for troppene I Sibir ca 1918–19&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Propagandaposter_voor_Amerikaanse_troepen_in_Siberie_in_1918-1919-1-.jpeg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P048.jpg",
        "entrythumblink":"thumbs/P048.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P048 | Tysk valgplakat 1920&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Nazi_poster_Teutonic_Knights_%281920%29.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P049.jpg",
        "entrythumblink":"thumbs/P049.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P049 | Sovjetisk antifascistisk propagandaplakat 1939&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Fascism_enemy_of_culture.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P050.jpg",
        "entrythumblink":"thumbs/P050.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P050 | Sovjetisk propagandaplakat for kollektivbruk 1930-tallet&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:442px-Kolkhozianos.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P051.jpg",
        "entrythumblink":"thumbs/P051.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P051 | Tysk propagandaplakat 3.rike&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;images/p051.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P052.jpg",
        "entrythumblink":"thumbs/P052.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P052 | Tysk propagandaplakat 3.rike&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;images/p052.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P053.jpg",
        "entrythumblink":"thumbs/P053.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P053 | Tysk propagandaplakat 3.rike&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;images/p053.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P054.jpg",
        "entrythumblink":"thumbs/P054.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P054 | Tysk propagandaplakat 3.rike&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;images/p054.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P055.jpg",
        "entrythumblink":"thumbs/P055.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P055 | Tysk propagandaplakat 3.rike&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;images/p055.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P056.jpg",
        "entrythumblink":"thumbs/P056.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P056 | Tysk propagandaplakat 3.rike&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;images/p056.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P057.jpg",
        "entrythumblink":"thumbs/P057.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P057 | Tysk propagandaplakat 3.rike&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;images/p057.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P058.jpg",
        "entrythumblink":"thumbs/P058.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P058 | Russisk propagandaplakat 1919 &lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:EhffvnaPninyelCbfgre.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P059.jpg",
        "entrythumblink":"thumbs/P059.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P059 | Sovjetisk propagandaplakat 1918&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:I._Nivinskiy_-_Women,_Go_into_Cooperatives_%281918%29.jpeg &apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P059b.jpg",
        "entrythumblink":"thumbs/P059b.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P059b | Sovjetisk propagandaplakat for verdensrevolusjonen 1931&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:The_Road_to_Worldwide_October.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P059c.jpg",
        "entrythumblink":"thumbs/P059c.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P059c | Sovjetisk propagandaplakat for verdensrevolusjonen 1922&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:CominternIV.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"}]},

        {"title":"2.VERDENSKRIG ALLIERTE |",
        "entry":[
        {"entrytype":"image",
        "entrylink":"images/P060.jpg",
        "entrythumblink":"thumbs/P060.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P060 | Amerikansk propagandaplakat 1944&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Flickr_-_%E2%80%A6trialsanderrors_-_Sad_puppy_propaganda_poster,_1944.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P061.jpg",
        "entrythumblink":"thumbs/P061.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P061 | Amerikansk propagandaplakat 2.verdenskrig&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Ww2_poster_oct0404.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P062.jpg",
        "entrythumblink":"thumbs/P062.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P062 | Amerikansk propagandaplakat for å hjelpe Kina i krigen mot Japan 1930-tallet&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:China_Relief_Fund.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P063.jpg",
        "entrythumblink":"thumbs/P063.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P063 | Australsk propagandaplakat 2.verdenskrig&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:He%27s_coming_South.jpg &apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P064.jpg",
        "entrythumblink":"thumbs/P064.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P064 | Amerikansk propagandaplakat 2.verdenskrig&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:JeanCarluProduction.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P065.jpg",
        "entrythumblink":"thumbs/P065.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P065 | Britisk propagandaplakat 2.verdenskrig&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Lidice_shall_live.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P066.jpg",
        "entrythumblink":"thumbs/P066.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P066 | Britisk propagandaplakat 2.verdenskrig&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Kriegsplakate_6_db.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P067.jpg",
        "entrythumblink":"thumbs/P067.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P067 | Amerikansk propagandaplakat 2.verdenskrig&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Afficheamericaine2.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P068.jpg",
        "entrythumblink":"thumbs/P068.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P068 | Amerikansk propagandaplakat 2.verdenskrig&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:AntiJapanesePropagandaTakeDayOff.gif &apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P069.jpg",
        "entrythumblink":"thumbs/P069.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P069 | Amerikansk propagandaplakat 2.verdenskrig&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:PropagandaHitlerTojo.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P070.jpg",
        "entrythumblink":"thumbs/P070.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P070 | Amerikansk propagandaplakat 2.verdenskrig&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Tokio_Kid_Say.png&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P071.jpg",
        "entrythumblink":"thumbs/P071.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P071 | Amerikansk propagandaplakat 2.verdenskrig&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Fagbag.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P072.jpg",
        "entrythumblink":"thumbs/P072.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P072 | Amerikansk propagandaplakat 2.verdenskrig&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Ride_with_hitler.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P073.jpg",
        "entrythumblink":"thumbs/P073.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P073 | Amerikansk propagandaplakat 1944&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:1944_JonWhitcomb_USNavy_%283214638694%29.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P074.jpg",
        "entrythumblink":"thumbs/P074.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P074 | Amerikansk propagandaplakat 2.verdenskrig&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Poster_russian.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P075.jpg",
        "entrythumblink":"thumbs/P075.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P075 | Amerikansk propagandaplakat 2.verdenskrig&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:PropagandaNaziJapaneseMonster.gif &apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"}]},

        {"title":"2.VERDENSKRIG TYSKE |",
        "entry":[
        {"entrytype":"image",
        "entrylink":"images/P100.jpg",
        "entrythumblink":"thumbs/P100.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P100 | Tysk antisovjetisk plakat på polsk 2.verdenskrig&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:German_antisemitic_and_anti-Soviet_poster.JPG&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P101.jpg",
        "entrythumblink":"thumbs/P101.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P101 | Tysk propagandaplakat for å verve belgiere til Waffen-SS&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:SSWallonie.jpeg &apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P102.jpg",
        "entrythumblink":"thumbs/P102.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P102 | Berlin april 1945&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Bundesarchiv_Bild_183-J31423,_Berlin,_Durchhalteparole_zwischen_Tr%C3%BCmmern.jpg &apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P103.jpg",
        "entrythumblink":"thumbs/P103.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P103 | Tysk propagandaplakat 1943&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Schafft_Waffen_an_die_Front_-_Sommer_1943.png &apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P104.jpg",
        "entrythumblink":"thumbs/P104.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P104 | Tysk propagandaplakat for blending ca 1940&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Der_Feind_sieht_Dein_Licht_%28ca._1940%29.png&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P105.jpg",
        "entrythumblink":"thumbs/P105.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P105 | Tysk antisemittisk plakat på polsk 1942&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:German_antisemitic_poster,_1942.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P106.jpg",
        "entrythumblink":"thumbs/P106.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P106 | Tysk antisovjetisk propagandaplakat på polsk 1943&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:German_anti-Soviet_poster.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P108.jpg",
        "entrythumblink":"thumbs/P108.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P108 | Tysk propagandaseddel utløst fra rakett over London 1944&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:NaziV-WaffenRocketPropagandaleaflet1944june.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P109.jpg",
        "entrythumblink":"thumbs/P109.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P109 | Tysk verveplakat for Waffen SS på nederlandsk 2.verdenskrig&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Ssnederland.jpg &apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P110.jpg",
        "entrythumblink":"thumbs/P110.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P110 | Tysk antiengelsk propagandaplakater 1940 i Frankrike&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Bundesarchiv_Bild_183-L12579,_Frankreich,_Anti-englische_Plakate.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P111.jpg",
        "entrythumblink":"thumbs/P111.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P111 | Tysk antisovjetisk plakat på russisk 1943&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Vinnycia01.JPG&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P112.jpg",
        "entrythumblink":"thumbs/P112.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P112 | Tysk frimerke 1945&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;images/P112.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P113.jpg",
        "entrythumblink":"thumbs/P113.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P113 | Tysk frimerke 1943&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;images/P113.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P114.jpg",
        "entrythumblink":"thumbs/P114.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P114 | Tysk frimerke 1943&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;images/P114.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P115.jpg",
        "entrythumblink":"thumbs/P115.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P115 | Rekrutteringsplakat for franskmenn inn i Waffen SS&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:French_SS_recruitment_poster.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P116.jpg",
        "entrythumblink":"thumbs/P116.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P116 | Tysk propagandaplakat laget for Ukraina 1942 ”Befrieren Hitler”&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Gitler-vizvolitel.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"}]},

        {"title":"2.VERDENSKRIG SOVJETISKE |",
        "entry":[
        {"entrytype":"image",
        "entrylink":"images/P130.jpg",
        "entrythumblink":"thumbs/P130.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P130 | Sovjetisk propagandaplakat som viser sovjetiske soldater som “befrir”polakker 1939&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Armiya_osvobozhdenya.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P131.jpg",
        "entrythumblink":"thumbs/P131.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P131 | Sovjetisk propagandaplakat mot spioner 2.verdenskrig&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Bolsheviks_to_the_end.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P132.jpg",
        "entrythumblink":"thumbs/P132.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P132 | Sovjetisk propagandaplakat 2.verdenskrig&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Ussr0454.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P133.jpg",
        "entrythumblink":"thumbs/P133.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P133 | Sovjetisk propagandaplakat 2.verdenskrig&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Nazitiger1.jpg &apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P134.jpg",
        "entrythumblink":"thumbs/P134.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P134 | Sovjetisk propagandaplakat 2.verdenskrig&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Ussr0463.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P135.jpg",
        "entrythumblink":"thumbs/P135.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P135 | Sovjetiske propagandaplakater 2.verdenskrig på jubileumsfrimerker&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Kvartblok_55_years_of_Victory,_Russia,_2000.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P136.jpg",
        "entrythumblink":"thumbs/P136.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P136 | Sovjetisk propagandaplakat 2.verdenskrig&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Ussr0182.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P137.jpg",
        "entrythumblink":"thumbs/P137.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P137 | Sovjetisk propagandaplakat 2.verdenskrig&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Ussr0512.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"}]},

        {"title":"2.VERDENSKRIG JAPANSKE |",
        "entry":[
        {"entrytype":"image",
        "entrylink":"images/P150.jpg",
        "entrythumblink":"thumbs/P150.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P150 | Japansk propagandaplakat 2.verdenskrig&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Organize_Labor_Service_Corps.JPG&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P151.jpg",
        "entrythumblink":"thumbs/P151.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P151 | Japansk propagandaplakat 2.verdenskrig&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:This_ballot_is_a_power_for_creation_of_Greater_East_Asia.JPG&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P152.jpg",
        "entrythumblink":"thumbs/P152.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P152 | Japansk propagandaplakat 1938&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:1938_Naka_yoshi_sangoku.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"}]},

        {"title":"ETTERKRIGSTIDEN KOREAKRIGEN |",
        "entry":[
        {"entrytype":"image",
        "entrylink":"images/P170.jpg",
        "entrythumblink":"thumbs/P170.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P170 | Kinesisk propagandaplakat der kinesere og nordkoreanere kjemper sammen 1950-tallet&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:1950s_%E5%85%A8%E5%8A%9B%E6%94%AF%E6%8C%81.jpeg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P171.jpg",
        "entrythumblink":"thumbs/P171.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P171 | Kinesisk propagandaplakat Koreakrigen 1950-tallet&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:1950s_%E4%B8%AD%E5%9C%8B%E4%BA%BA%E6%B0%91%E5%86%B3%E4%B8%8D%E8%83%BD%E5%AE%B9%E5%BF%8D.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"}]},

        {"title":"ETTERKRIGSTIDEN SOVJET |",
        "entry":[
        {"entrytype":"image",
        "entrylink":"images/P175.jpg",
        "entrythumblink":"thumbs/P175.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P175 | Sovjetisk propagandaplakat mot NATO,1940-tallet&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Poster31.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P176.jpg",
        "entrythumblink":"thumbs/P176.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P176 | Sovjetisk plakat 1940-tallet&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Poster14.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P177.jpg",
        "entrythumblink":"thumbs/P177.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P177 | Sovjetisk propagandaplakat 1940-tallet&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://www.flickr.com/photos/40143737@N02/3941717578&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P178.jpg",
        "entrythumblink":"thumbs/P178.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P178 | Sovjetisk propagandaplakat 1952&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Poster18.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P179.jpg",
        "entrythumblink":"thumbs/P179.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P179 | Sovjetisk propagandaplakat med Stalin 1940-tallet&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Poster27.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"}]},

        {"title":"ETTERKRIGSTIDEN KINA |",
        "entry":[
        {"entrytype":"image",
        "entrylink":"images/P180.jpg",
        "entrythumblink":"thumbs/P180.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P180 | Formann Mao i kornåkeren 1958&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:People%27s_commune1.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P181.jpg",
        "entrythumblink":"thumbs/P181.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P181 | Kinesisk propagandaplakat for å “befri” Taiwan 1954–56&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:%E4%B8%80%E5%AE%9A%E8%A6%81%E8%A7%A3%E6%94%BE%E5%8F%B0%E6%B9%BE.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P182.jpg",
        "entrythumblink":"thumbs/P182.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P182 | Kinesisk propagandaplakat for å “befri” Taiwan 1954–56&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:1954_%E6%88%91%E4%BB%AC%E5%A0%85%E5%86%B3.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P183.jpg",
        "entrythumblink":"thumbs/P183.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P183 | Kinesisk propagandaplakat 1952&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:1950s_%E6%AF%9B%E4%B8%BB%E5%B8%AD%E7%BB%99%E6%88%91%E4%BB%AC%E7%9A%84%E5%B9%B8%E7%A6%8F%E7%94%9F%E6%B4%BB.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P184.jpg",
        "entrythumblink":"thumbs/P184.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P184 | Kinesisk propagandaplakat for å “frigjøre” Taiwan 1950-tallet&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:1950s_%E8%A7%A3%E6%94%BE%E8%BB%8D%E5%8F%94%E5%8F%94.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P185.jpg",
        "entrythumblink":"thumbs/P185.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P185 | Kinesisk propagandaplakat 1952&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:1952_%E8%BB%8D%E4%BA%8B%E6%94%B9%E9%9D%A9.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P186.jpg",
        "entrythumblink":"thumbs/P186.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P186 | Kinesisk propagandaplakat 1954&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:1954_%E5%A0%85%E5%86%B3%E8%A7%A3%E6%94%BE%E5%8F%B0%E6%B9%BE.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P187.jpg",
        "entrythumblink":"thumbs/P187.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P187 | Kinesisk plakat som viser arrestasjon av antirevolusjonære 1951&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Suppress_counterrevolutionaries%281951%29.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P188.jpg",
        "entrythumblink":"thumbs/P188.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P188 | Kinesisk propagandaplakat 1950-tallet&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:World_revolution1.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"}]},

        {"title":"ETTERKRIGSTIDEN USA |",
        "entry":[
        {"entrytype":"image",
        "entrylink":"images/P190.jpg",
        "entrythumblink":"thumbs/P190.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P190 | Amerikansk propagandaplakat 1950&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Europe_Plan_Marshall._Poster_1947.JPG&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P191.jpg",
        "entrythumblink":"thumbs/P191.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P191 | Omslag amerikansk propagandabok 1947&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Is_this_tomorrow.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P192.jpg",
        "entrythumblink":"thumbs/P192.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P192 | Amerikansk løpeseddel brukt I Afghanistan 2000-tallet&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:US_PsyOps_leaflet.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"}]},

        {"title":"ETTERKRIGSTIDEN DIVERSE |",
        "entry":[
        {"entrytype":"image",
        "entrylink":"images/P200.jpg",
        "entrythumblink":"thumbs/P200.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P200 | Utendørs plakat Cuba 2009&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Fidel_venceremos_Santiago_4175v.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P201.jpg",
        "entrythumblink":"thumbs/P201.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P201 | Iransk graffiti på den amerikanske ambassaden i Teheran ca 1980&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Teheran_US_embassy_propaganda_grasp_unedited.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P202.jpg",
        "entrythumblink":"thumbs/P202.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P202 | Nordkoreansk plakat 2008&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Kim_Il-sung.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"}]},

        {"title":"KARIKATURER |",
        "entry":[
        {"entrytype":"image",
        "entrylink":"images/P210.jpg",
        "entrythumblink":"thumbs/P210.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P210 | Tysk karikatur 1918 som viser “dolkestøtlegenden”&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Stab-in-the-back_postcard.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P211.jpg",
        "entrythumblink":"thumbs/P211.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P211 | Fransk antitysk karikatur 1915,“Altfor hard”&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Guerre_14-18-Humour-L%27ingordo,_trop_dur-1915.JPG&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P212.jpg",
        "entrythumblink":"thumbs/P212.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P212 | Svensk karikatur 2008 mot å sende svenske tropper til Afghanistan&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Taliban.jpg?uselang=nn&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P213.jpg",
        "entrythumblink":"thumbs/P213.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P213 | Sovjetisk antifinsk karikatur 1939&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Spravka.jpg?uselang=nn&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"}]},

        {"title":"NS-PROPAGANDA |",
        "entry":[
        {"entrytype":"image",
        "entrylink":"images/P250.jpg",
        "entrythumblink":"thumbs/P250.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P250 | NS-plakat fra okkupasjonstiden verver for frontkjempertjeneste&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;images/P250.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P251.jpg",
        "entrythumblink":"thumbs/P251.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P251 | NS-plakat fra okkupasjonstiden&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;images/P251.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P252.jpg",
        "entrythumblink":"thumbs/P252.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P252 | NS-plakat fra okkupasjonstiden&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;images/P252.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P253.jpg",
        "entrythumblink":"thumbs/P253.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P253 | NS-plakat fra okkupasjonstiden&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;images/P253.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P254.jpg",
        "entrythumblink":"thumbs/P254.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P254 | NS-plakat fra okkupasjonstiden&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;images/P254.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P255.jpg",
        "entrythumblink":"thumbs/P255.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P255 | NS-plakat fra okkupasjonstiden&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;images/P255.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P256.jpg",
        "entrythumblink":"thumbs/P256.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P256 | Valgplakat for NS&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;images/P256.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P257.jpg",
        "entrythumblink":"thumbs/P257.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P257 | NS-plakat fra okkupasjonstiden&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;images/P257.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P258.jpg",
        "entrythumblink":"thumbs/P258.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P258 | NS-plakat for verving til Skijegerbataljonen&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;images/P258.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P259.jpg",
        "entrythumblink":"thumbs/P259.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P259 | Brev fra okkupasjonstiden med frontkjempermerker&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;images/P259.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P260.jpg",
        "entrythumblink":"thumbs/P260.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P260 | Brev fra okkupasjonstiden med Quislingfrimerke&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;images/P260.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P261.jpg",
        "entrythumblink":"thumbs/P261.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P261 | Brev fra okkupasjonstiden med særstempel&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;images/P261.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P263.jpg",
        "entrythumblink":"thumbs/P263.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P263 | Brev fra okkupasjonstiden&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;images/P263.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P264.jpg",
        "entrythumblink":"thumbs/P264.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P264 | Brev fra okkupasjonstiden med Quislingfrimerker&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;images/P264.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P265.jpg",
        "entrythumblink":"thumbs/P265.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P265 | Brev fra okkupasjonstiden med V-stempel og sensur&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;images/P265.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P266.jpg",
        "entrythumblink":"thumbs/P266.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P266 | Brev med Londonregjeringens frimerkeserie&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;images/P266.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P270.jpg",
        "entrythumblink":"thumbs/P270.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P270 | Forsiden på vervebrosjyre for frontkjempere 2.verdenskrig&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;images/P270.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P270b.jpg",
        "entrythumblink":"thumbs/P270b.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P270b | Innholdet i vervebrosjyre for frontkjempere 2.verdenskrig&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;images/P270b.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P271.jpg",
        "entrythumblink":"thumbs/P271.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P271 | Forsiden på NS-bildemagasinet Munin 1944&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;images/P271.pdf&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P273.jpg",
        "entrythumblink":"thumbs/P273.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P273 | Forsiden på NS-magasinet Nasjonalungdommen&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;images/P273.pdf&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P276.jpg",
        "entrythumblink":"thumbs/P276.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P276 | Forsiden av NS-magasinet Huginn &lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;images/P276.pdf&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P277.jpg",
        "entrythumblink":"thumbs/P277.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P277 | Brev fra okkupasjonstiden med frimerker fra Snorreserien&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;images/P277.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P278.jpg",
        "entrythumblink":"thumbs/P278.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P278 | Brev fra okkupasjonstiden med frimerker fra Snorreserien&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;images/P278.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P279.jpg",
        "entrythumblink":"thumbs/P279.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P279 | Brev fra okkupasjonstiden med særstempel&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;images/P279.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P280.jpg",
        "entrythumblink":"thumbs/P280.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P280 | Brev fra okkupasjonstiden med frontkempermerke og tysk sensur&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;images/P280.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P281.jpg",
        "entrythumblink":"thumbs/P281.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P281 | Forsiden av Alle Kvinners blad 1941&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;images/P281.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P282.jpg",
        "entrythumblink":"thumbs/P282.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P282 | NS-plakat fra okkupasjonstiden&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;images/P282.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P283.jpg",
        "entrythumblink":"thumbs/P283.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P283 | Propagandafrimerke utgitt av Londonregjeringen&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;images/P283.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P284.jpg",
        "entrythumblink":"thumbs/P284.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P284 | Propagandafrimerke utgitt av Londonregjeringen&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;images/P284.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"},

        {"entrytype":"image",
        "entrylink":"images/P285.jpg",
        "entrythumblink":"thumbs/P285.jpg",
        "videopreviewimage":"",
        "$t":"&lt;h1&gt;P285 | NS-plakat Norge 1942&lt;/h1&gt;\n\t \t\t\t&lt;p&gt;&lt;a href=&apos;http://commons.wikimedia.org/wiki/File:Propaganda_poster_Norway_1942.jpg&apos; target=&apos;_blank&apos;&gt;Last ned&lt;/a&gt;&lt;/p&gt;"}
        ]
        }
        ]
}
}
